#!/bin/bash

name=c-ares
version=1.34.6
tarball_url="https://github.com/c-ares/c-ares/releases/download/v${version}/c-ares-${version}.tar.gz"
tarball_blake2b="3a348cfaf4c992ba1712be73907599fd9d3e7b6d1b5498fa86259bbd8c9e102d530e89eee0f668b5b0b8164034047c187be7f8d40016d012c9e451dbf56bfbde"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
