#!/bin/bash

make_ca_version=1.16.1

name=ca-certificates
version="$(. "${base_dir}/recipes/nss" && echo "${version}")"
tarball_url="https://github.com/lfs-book/make-ca/archive/v${make_ca_version}/make-ca-${make_ca_version}.tar.gz"
tarball_blake2b="f054fe6e96b74bfc02038e9dc4dd09628a22b75711f692a346c4952a6fa07456b63cff7863d3c11feddeb1ef37b1b786934e2713008b808570da8443e978ece3"
revision=1
imagedeps="p11-kit"
hostdeps="gcc pkgconf"
deps="core-libs nss openssl p11-kit"

build() {
    cp -rp "${source_dir}"/. ./
}

package() {
    chmod +x ./make-ca

    ./make-ca -f -C "${sysroot_dir}${prefix}/share/nss/certdata.txt" -D "${dest_dir}"

    # Remove unneeded systemd timers
    rm -rvf "${dest_dir}${prefix}/lib"

    post_package_strip
}
