#!/bin/bash

name=dbus-bootstrap
from_source=dbus
revision=1
bootstrap_pkg=yes
hostdeps="gcc pkgconf"
deps="core-libs libexpat"

configure() {
    meson_configure \
        -Druntime_dir=/run \
        -Dsystemd_system_unitdir=no \
        -Dsystemd_user_unitdir=no \
        -Dsystem_pid_file=/run/dbus/pid \
        -Dsystem_socket=/run/dbus/system_bus_socket \
        -Dselinux=disabled \
        -Dapparmor=disabled \
        -Dlibaudit=disabled \
        -Dkqueue=disabled \
        -Dlaunchd=disabled \
        -Dsystemd=disabled \
        -Dmodular_tests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
