#!/bin/bash

name=fastfetch
version=2.56.1
git_url="https://github.com/fastfetch-cli/fastfetch.git"
commit=a9f43ff466ad9ba47222c795d2725f721a86eac0
revision=1
hostdeps="gcc pkgconf"
deps="core-libs sqlite zlib"

configure() {
    cmake_configure \
        -DBUILD_FLASHFETCH=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
