#!/bin/bash

name=findutils
version=4.10.0
tarball_url="https://ftp.gnu.org/gnu/findutils/findutils-${version}.tar.xz"
tarball_blake2b="2eebdcb425c04170d17afb80e7270ba095bd691660d961dcfa731141633d3bb597d0b47d69ed17e891ef884a36d4c232885097e45b41d3d3ac79dbeae6ee2282"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    autotools_configure \
        --without-selinux
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
