#!/bin/bash

name=fmt
version=12.1.0
git_url="https://github.com/fmtlib/fmt.git"
commit=407c905e45ad75fc29bf0f9bb7c5c2fd3475976f
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    cmake_configure \
        -DFMT_TEST=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
