#!/bin/bash

name=freetype2
version=2.14.1
git_url="https://gitlab.freedesktop.org/freetype/freetype.git"
commit=526ec5c47b9ebccc4754c85ac0c0cdf7c85a5e9b
revision=1
hostdeps="gcc pkgconf"
deps="core-libs brotli bzip2 libpng zlib"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
