#!/bin/bash

name=freetype2-bootstrap
from_source=freetype2
revision=1
bootstrap_pkg=yes
hostdeps="gcc pkgconf"
deps="core-libs brotli bzip2 libpng zlib"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
