#!/bin/bash

name=garcon
version=4.21.0
tarball_url="https://archive.xfce.org/src/xfce/garcon/${version%.*}/garcon-${version}.tar.xz"
tarball_blake2b="0fa1f4224aacb2e5f399aaf2899c48c59e84d470f49f383ac55d1be879a301ba77ef89cd16ba8cdce0b3eaabbeb5217397b271177c1660ed77d8594afc26746d"
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs dbus glib2 gtk3 libxfce4ui libxfce4util"

configure() {
    meson_configure \
        -Dintrospection=true
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
