#!/bin/bash

name=gavl
version=1.4.0
tarball_url="https://downloads.sourceforge.net/gmerlin/gavl-${version}.tar.gz"
tarball_blake2b="2ed47cf63d8ce3424d0714e202a11ecef89c5a9c160a6045e238bae4179c02398600fc9c6d914784bb24a86c501f93971631461bdecaa8a70743a674748a2ec3"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
        LIBS=-lm \
    autotools_configure \
        --with-cpuflags=none
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
