#!/bin/bash

name=gawk
version=5.3.2
tarball_url="https://ftp.gnu.org/gnu/gawk/gawk-${version}.tar.xz"
tarball_blake2b="8536777bb45c63d737ef08b3f1b98285cb29ec54400e35b2139c2bc66b464e3ec4950274614d95d94dc7eae18c57333b7c30a44d993855258155fc82b749042a"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs mpfr gmp readline"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
