#!/bin/bash

name=gdk-pixbuf
version=2.44.4
git_url="https://gitlab.gnome.org/GNOME/gdk-pixbuf.git"
commit=c9e6d11cbfa085d7b59dd6ad3b1cbfa26348ce13
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs glib2 libjpeg-turbo libpng libtiff libx11 util-linux"

configure() {
    meson_configure \
        -Dintrospection=enabled \
        -Dglycin=disabled \
        -Dgio_sniffing=false \
        -Dman=false
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
