#!/bin/bash

name=glib2-bootstrap
from_source=glib2
revision=1
bootstrap_pkg=yes
hostdeps="gcc pkgconf"
deps="core-libs libffi pcre2 zlib"

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=disabled \
        -Dsysprof=disabled \
        -Dintrospection=disabled \
        -Dxattr=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
