#!/bin/bash

name=glib2
version=2.86.3
tarball_url="https://download.gnome.org/sources/glib/${version%.*}/glib-${version}.tar.xz"
tarball_blake2b="eb98aa210a988cfe9060a8bf9ca594e52016f68ac33ee07e75d8fd2f3af70a2046b9c0af4a50a7a66369030156b48e0baa5041dbdd47b60361cb90b1a1de11eb"
revision=1
imagedeps="build-essential patchelf python3-docutils"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs gobject-introspection libffi pcre2 zlib"

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=enabled \
        -Dsysprof=disabled \
        -Dintrospection=enabled \
        -Dxattr=true
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
