#!/bin/bash

name=glibc
version=2.42
tarball_url="https://ftp.gnu.org/gnu/glibc/glibc-${version}.tar.xz"
tarball_blake2b="6ffabfe7942034a5a4fb5097679cb47bc3431eb2a3864af07cea0cb6aa5db63fbaf6f026b3c9299e00268058a6762eb21e92499f012d552ed87d65c7ffbd0bbe"
revision=1
hostdeps="gcc-bootstrap pkgconf"
deps="linux-headers"

configure() {
    # glibc handles fortify internally via --enable-fortify-source.
    # Remove any -D_FORTIFY_SOURCE from TARGET_CFLAGS to avoid conflicts.
    TARGET_CFLAGS="${TARGET_CFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"

    echo "slibdir=${prefix}/lib" >>configparms
    echo "rtlddir=${prefix}/lib" >>configparms
    echo "sbindir=${prefix}/bin" >>configparms
    echo "rootsbindir=${prefix}/bin" >>configparms

    autotools_configure \
        --with-headers="${sysroot_dir}${prefix}"/include \
        --enable-bind-now \
        --enable-cet \
        --enable-fortify-source \
        --enable-stack-protector=strong \
        --disable-nscd \
        --disable-profile \
        --disable-timezone-tools \
        --disable-werror
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install
}
