#!/bin/bash

name=gobject-introspection
version=1.86.0
tarball_url="https://download.gnome.org/sources/gobject-introspection/${version%.*}/gobject-introspection-${version}.tar.xz"
tarball_blake2b="425d60c8c4bd582c55030ed91b4c2f3982e3c502da1c6f2579c4cc1e05d82d8a8c9a533af3e4a7ae8f6a031761d763d7f7ad8031e38ae3bd7d2549c9f6bcf7f3"
revision=1
imagedeps="build-essential gobject-introspection libpython3-dev patchelf"
hostdeps="gcc pkgconf"
deps="core-libs glib2-bootstrap python"

configure() {
    meson_configure \
        -Dgtk_doc=false \
        -Dgi_cross_use_prebuilt_gi=true \
        -Dtests=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
