#!/bin/bash

name=graphene
version=1.10.8
tarball_url="https://download.gnome.org/sources/graphene/1.10/graphene-${version}.tar.xz"
tarball_blake2b="61eb18994ce833838c746dad6650df61acf6de3d4742f136d8f877aa9db5c49d310c01d1a80a558250e2dafacab23181ac29506ea18db6308c53b9305411919a"
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs glib2"

configure() {
    meson_configure \
        -Dintrospection=enabled \
        -Dtests=false \
        -Dinstalled_tests=false
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
