#!/bin/bash

name=gtk-layer-shell
version=0.10.0
tarball_url="https://github.com/wmww/gtk-layer-shell/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="72448dea465b2fbc4af8f3abf538678de419bc5d6ada88252f5ee0dd43b00ee7647d91a8058faafaee10933eadac988aecc079fa1b503dfcfcf2cc58627cbeab"
revision=1
imagedeps="build-essential libwayland-bin patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs glib2 gtk3 wayland"

configure() {
    meson_configure \
        -Dvapi=false
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
