#!/bin/bash

name=json-c
version=0.18
git_url="https://github.com/json-c/json-c.git"
commit="41a55cfcedb54d9c1874f2f0eb07b504091d7e37"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
