#!/bin/bash

name=less
version=685
tarball_url="https://www.greenwoodsoftware.com/less/less-${version}.tar.gz"
tarball_blake2b="771ba2fb1f593e80d9e5e203bfe9b7a8a33833fcd3464a0c64c4056359e9ecc723eff87b783c9ab4c3090d7dac1973c1875eb7d926601c512dc0494e7e8adb5c"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs ncurses"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    post_package_strip
}
