#!/bin/bash

name=libaom
version=3.12.1
tarball_url="https://storage.googleapis.com/aom-releases/libaom-${version}.tar.gz"
tarball_blake2b="4fa4ea0620b27013d2c39589ea5bc4333ea26ffe51dad64e95b240cdf5c82fcd0810fecf45410f34b89057d9000c93efae106c49e4017796d7c8b2752357709d"
revision=1
imagedeps="yasm"
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    cmake_configure \
        -DENABLE_DOCS=no
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    rm -v "${dest_dir}${prefix}/lib/libaom.a"

    post_package_strip
}
