#!/bin/bash

name=libavif
version=1.2.1
tarball_url="https://github.com/AOMediaCodec/libavif/archive/v${version}/libavif-${version}.tar.gz"
tarball_blake2b="2ddfe956779691711e06641fc0cd210e9bdf4801ddc5898cd544117409ae37abbbcd6c07704f063b2cbc383dc30dd7367b8f8fdd2de584cccd3324c4f3a71b3d"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs gdk-pixbuf libaom"

configure() {
    cmake_configure \
        -DAVIF_CODEC_AOM=SYSTEM \
        -DAVIF_BUILD_GDK_PIXBUF=ON \
        -DAVIF_LIBYUV=OFF
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    cat <<'EOF' >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/usr/bin:/usr/local/bin:/usr/local/sbin"

ACTION="$1"

case "${ACTION}" in
pre)
    ;;
post)
    gdk-pixbuf-query-loaders --update-cache
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL

    post_package_strip
}
