#!/bin/bash

name=libcloudproviders
version=0.3.6
tarball_url="https://download.gnome.org/sources/libcloudproviders/0.3/libcloudproviders-${version}.tar.xz"
tarball_blake2b="af5864fa9f4de8842dce80efb53b7b6ff73a679589a49b4edf55c77e0e49114dd5da8dbdc6950574a758483b09168e90e27ded05b0ef501bf9b454341196f7ff"
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs glib2"

configure() {
    meson_configure \
        -Dvapigen=false
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
