#!/bin/bash

name=libcddb
version=1.3.2
tarball_url="https://downloads.sourceforge.net/libcddb/libcddb-${version}.tar.bz2"
tarball_blake2b="8386ea051f23004396d53ad228a595d13c8c194361223026e901ff859f8e3d2dadb93d5e779902ec4698c164a3e06073fc82f331b22b4cf42f5ab8b1fae562e6"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
