#!/bin/bash

name=libdrm
version=2.4.131
tarball_url="https://dri.freedesktop.org/libdrm/libdrm-${version}.tar.xz"
tarball_blake2b="e83e9cdde629fbab3a23170c964952c13dcb75e1b96773088392833f31b44f55903e01e28fc4c7d5e18c7f4fab306a5b0c8f4d4d76e5eeaac33ad3b350685a89"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libpciaccess"

configure() {
    meson_configure \
        -Dudev=true \
        -Detnaviv=disabled \
        -Dfreedreno=disabled \
        -Dvc4=disabled \
        -Dvalgrind=disabled \
        -Dtests=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
