#!/bin/bash

name=libexpat
version=2.7.3
git_url="https://github.com/libexpat/libexpat.git"
commit=4575e52f83e0d6d7bd24939eab8952bbc7bc358f
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
        cmake_source_dir="${source_dir}/expat" \
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
