#!/bin/bash

name=libfontenc
version=1.1.8
tarball_url="https://www.x.org/archive/individual/lib/libfontenc-${version}.tar.gz"
tarball_blake2b="6d613cf17a3414fadb3961eea5493de33bbcdc6d19909d1ac7fa10d9b9c4eba59478f5fa59ac4758a86307fb2c04f40dbcc345203be9161e939de73bc7f93d3a"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs xorg-proto zlib"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
