#!/bin/bash

name=libjxl
version=0.11.1
tarball_url="https://github.com/libjxl/libjxl/archive/v${version}/libjxl-${version}.tar.gz"
tarball_blake2b="e2a96464fdcdff483de92e0f3301870a62f934976e6d78fd1efe30fe96f30ce6c3459843385712df7914ad53aeff3de1b84ac1a4d22294e909ed559d7c6c9db9"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs brotli gdk-pixbuf giflib highway lcms libavif libjpeg-turbo libwebp"

configure() {
    cmake_configure \
        -DBUILD_TESTING=OFF \
        -DJPEGXL_ENABLE_SKCMS=OFF \
        -DJPEGXL_ENABLE_SJPEG=OFF \
        -DJPEGXL_ENABLE_PLUGINS=ON
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    # Move installed pixbuf loaders to the correct location.
    mv "${dest_dir}${sysroot_dir}${prefix}"/lib/gdk-pixbuf-2.0/ "${dest_dir}${prefix}"/lib/
    rm -rfv ${dest_dir}${sysroot_dir}

    cat <<'EOF' >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/usr/bin:/usr/local/bin:/usr/local/sbin"

ACTION="$1"

case "${ACTION}" in
pre)
    ;;
post)
    gdk-pixbuf-query-loaders --update-cache
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL

    post_package_strip
}
