#!/bin/bash

name=libsm
version=1.2.6
tarball_url="https://www.x.org/archive/individual/lib/libSM-${version}.tar.gz"
tarball_blake2b="90bb1c08acc213cf0fbb766505d3f0973dab0ac989d1c76e88ef26a6cfedeeb27a7db06f8d3a794514888bcbc9998939978ffb4371ede330f8b98f3cb48b7a1b"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libice xorg-proto"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
