#!/bin/bash

name=libtiff
version=4.7.1
git_url="https://gitlab.com/libtiff/libtiff.git"
commit=5fe20d0e9aba49a6a350ed533459d1505203838f
revision=1
hostdeps="gcc pkgconf"
deps="core-libs freeglut libjpeg-turbo zlib zstd xz"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
