#!/bin/bash

name=libtirpc
version=1.3.7
tarball_url="https://downloads.sourceforge.net/libtirpc/libtirpc-${version}.tar.bz2"
tarball_blake2b="b6a42add32c1a8bef4d974bb6c527131c0215179a303360d902110b03ce2217280efcb8dcad3a4da00f7ab971a1376e0bc30d6e3ecf6f98f1d4c2161a9276f86"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    autotools_configure \
        --disable-gssapi
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
