#!/bin/bash

name=libvpx
version=1.15.2
tarball_url="https://github.com/webmproject/libvpx/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="3aac120f4d03cb7a8f29dbafa6d8359129a02302afce9a5a1a5b52a52575720b63d0c45e034b9ceb38a90579f7aaafb96553e2a2822a96d5d079dee5bf0b0f9c"
revision=1
imagedeps="build-essential nasm"
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
        ac_cv_func_malloc_0_nonnull=yes \
        ac_cv_func_calloc_0_nonnull=yes \
        ac_cv_func_realloc_0_nonnull=yes \
    "${source_dir}/configure" \
        --prefix=${prefix} \
        --enable-shared \
        --disable-static \
        --enable-pic \
        --enable-vp8 \
        --enable-vp9 \
        --enable-multithread \
        --enable-vp9-highbitdepth \
        --disable-examples \
        --disable-install-docs \
        --disable-docs
}

build() {
    make -j${parallelism} \
        HAVE_GNU_STRIP=no \
        CC="${OS_TRIPLET}-gcc" \
        LD="${OS_TRIPLET}-gcc" \
        CXX="${OS_TRIPLET}-g++" \
        AR="${OS_TRIPLET}-ar" \
        NM="${OS_TRIPLET}-nm"
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
