#!/bin/bash

name=libva
version=2.23.0
tarball_url="https://github.com/intel/libva/releases/download/${version}/libva-${version}.tar.bz2"
tarball_blake2b="1263f236fc5e78a2d2e4798268466b702c45fe7e18fdf68431373b6faef1be3f0922f1beb00115d25ff3105e1df50e601f7447e0f01ffdbfe1c54582a1dfe5f1"
revision=1
imagedeps="build-essential libwayland-bin pkg-config"
hostdeps="gcc pkgconf"
deps="core-libs libdrm libglvnd libx11 libxext libxfixes wayland-protocols"

configure() {
        CFLAGS="${TARGET_CFLAGS} -DENABLE_VA_MESSAGING" \
        LDFLAGS="${TARGET_LDFLAGS}" \
    meson_configure_noflags
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
