#!/bin/bash

name=libwnck
version=43.3
git_url="https://gitlab.gnome.org/GNOME/libwnck.git"
commit=75e56cf1d7ef1edd61516bdf25bf7fdee8b935f3
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs glib2 gtk3 libxres startup-notification"

configure() {
    meson_configure \
        -Dinstall_tools=true \
        -Dstartup_notification=enabled \
        -Dintrospection=enabled \
        -Dgtk_doc=false
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
