#!/bin/bash

name=libxi
version=1.8.2
tarball_url="https://www.x.org/archive/individual/lib/libXi-${version}.tar.gz"
tarball_blake2b="aa9bd4cdcc519bf8b9029766d07e160a2847f3f6808ae5a125f90cd84e8e981436e8cdce2cabe9d58eaba39946b88026d5814c6d19f2cc94e9e4cd69d6bc8e2d"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libxext libxfixes xorg-proto"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
