#!/bin/bash

name=libxfce4util
version=4.20.1
tarball_url="https://archive.xfce.org/src/xfce/libxfce4util/${version%.*}/libxfce4util-${version}.tar.bz2"
tarball_blake2b="6b5b4a72b364ebfe166743194a8277a4b7a302e6efcbdd2b5f9c3b15c48f4c8510990c6917402fd76e4ce29dadac871803344f3625dccb1c6631549bc7531ead"
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs glib2"

configure() {
    meson_configure \
        -Dintrospection=true
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
