#!/bin/bash

name=libxext
version=1.3.6
tarball_url="https://www.x.org/archive/individual/lib/libXext-${version}.tar.gz"
tarball_blake2b="1f137f06c237bafec737886484d990e686130e84c8af0db3f47a87e8970d953e8030872e3f0f8b4dff15cfd786fb15e13331fecc0b320f1cf75fbb1629ff970a"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs xorg-proto libx11"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
