#!/bin/bash

name=libxpresent
version=1.0.2
git_url="https://gitlab.freedesktop.org/xorg/lib/libxpresent.git"
commit=4d92149372461bf575e8a09b1064a2884c38c3aa
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11 libxext libxfixes libxrandr xorg-proto"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
