#!/bin/bash

name=libxfont2
version=2.0.7
tarball_url="https://www.x.org/archive/individual/lib/libXfont2-${version}.tar.gz"
tarball_blake2b="3a82122366751ee96ba3e7ce020a9e5845527539b787897c664d4dc2977772beab7f04d3890a10ee2697f0ae5b5d6838d1fe62cf1c7942799d6a8210d2e82b57"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs bzip2 fontconfig freetype2 libfontenc libx11 xorg-util-macros xorg-proto xtrans zlib"

configure() {
    autotools_configure \
        --with-bzip2 \
        --disable-devel-docs \
        --disable-selective-werror
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
