#!/bin/bash

name=libxtst
version=1.2.5
tarball_url="https://www.x.org/archive/individual/lib/libXtst-${version}.tar.gz"
tarball_blake2b="5a8569f8818dce0afccba3efac34a54c967e90350deba61fd52c061309105e17481b574d70b609243956447c1bffdff67892d6782206412310ef134ccb6f6736"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libxext libxi libx11 xorg-proto"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
