#!/bin/bash

name=libxdmcp
version=1.1.5
tarball_url="https://www.x.org/archive/individual/lib/libXdmcp-${version}.tar.gz"
tarball_blake2b="15120e372940c78749e62b240624a4b6b0f65a485d3591193e55615db8e77d44247814c04e5e58604ae1a12484d8c53eac1a5db982bfb34f721c6ab4036743c3"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs xorg-proto"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
