#!/bin/bash

name=libxinerama
version=1.1.5
tarball_url="https://www.x.org/archive/individual/lib/libXinerama-${version}.tar.gz"
tarball_blake2b="ac24af05ae483e7f8476cb5fdf901ae80c592a766387e9f662ceeae5906a55e8529b35fcd01b6893289007e30788fd9e3a507af95870acfa6b25b25b159024a5"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11 libxext xorg-proto xorg-util-macros"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
