#!/bin/bash

name=libxfixes
version=6.0.2
git_url="https://gitlab.freedesktop.org/xorg/lib/libxfixes.git"
commit=70d5b0e37f8a759f3dbc218f22954347ceed094a
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11 xorg-proto"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
