#!/bin/bash

name=libxshmfence
version=1.3.3
tarball_url="https://www.x.org/archive/individual/lib/libxshmfence-${version}.tar.gz"
tarball_blake2b="22191b13b00fca8717c81c43b77102b8cc720c81057ea8a3355404b61bcbd049a6f58c9ad0f9cf93c4d3e9a387795b5c206f3fc563dfe4c5061b042bc49569ff"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs xorg-proto"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
