#!/bin/bash

name=libxmu
version=1.2.1
tarball_url="https://www.x.org/archive/individual/lib/libXmu-${version}.tar.gz"
tarball_blake2b="79cb21601f19a72fc771bb7fbde59d0fd3febdcf8fc6c6def91e2d8d9a99df4c7a9e633d819fe93df0cbd774a642cf39d44219c1fdbc154be28ba9086571cbb6"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libxext libxt"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
