#!/bin/bash

name=libyaml
version=0.2.5
git_url="https://github.com/yaml/libyaml.git"
commit="2c891fc7a770e8ba2fec34fc6b545c672beb37e6"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    mkdir -p "${dest_dir}${prefix}/lib/pkgconfig"
    cat <<EOF >"${dest_dir}${prefix}/lib/pkgconfig/yaml-0.1.pc"
prefix=${prefix}
exec_prefix=\${prefix}
includedir=\${prefix}/include
libdir=\${prefix}/lib

Name: LibYAML
Description: Library to parse and emit YAML
Version: ${version}
Cflags: -I\${includedir}
Libs: -L\${libdir} -lyaml
EOF

    post_package_strip
}
