#!/bin/bash

name=nghttp3
version=1.14.0
tarball_url="https://github.com/ngtcp2/nghttp3/releases/download/v${version}/nghttp3-${version}.tar.xz"
tarball_blake2b="a2fbd584a6ddcc65947bbf1cba3ae41e88ce8805f49e0891efb002f8101845c3080be554db3c21fd0e5b55412c9252532ca31b74097ffbd6d88ab70ac7d01f29"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
