#!/bin/bash

name=openjpeg2
version=2.5.4
tarball_url="https://github.com/uclouvain/openjpeg/archive/v${version}/openjpeg-${version}.tar.gz"
tarball_blake2b="8bcb821c4a5b437ffc53fbe4017da4bc9579d7c349bf558fea4db7856e267030760845e529b6692053779fee170074fb18f3e75051914eb30cfc6d46d284fce6"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs lcms libpng libtiff"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
