#!/bin/bash

name=opus
version=1.6.1
tarball_url="https://downloads.xiph.org/releases/opus/opus-${version}.tar.gz"
tarball_blake2b="dda8fb4e30e5f22d2b37616902892dcc715a2886150ab54f67d61a90c60a03afee05fb7b56a0d88355db007bb4d72c8bd6de3d874a49767318a5bba115b1a613"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
