#!/bin/bash

name=pam
version=1.7.1
tarball_url="https://github.com/linux-pam/linux-pam/releases/download/v${version}/Linux-PAM-${version}.tar.xz"
tarball_blake2b="0a64d7dbf6bb7e3d2c36ea1f29c3217d3e43a1cc0ba8adf2ee8a117946a53bd26634ebd70ff3b99a72f7373df6694ee054dc7eddab04e43bbc8f5b0e9e56b3bc"
revision=3
imagedeps="build-essential"
hostdeps="gcc pkgconf"
deps="core-libs elogind gdbm libnsl libtirpc"

configure() {
    meson_configure \
        -Dsecuredir="${prefix}/lib/security" \
        -Dpam_unix=enabled \
        -Delogind=enabled \
        -Dpam_lastlog=enabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    rm -fv "${dest_dir}"/etc/pam.d/other
    chmod -v 4755 "${dest_dir}${prefix}"/bin/unix_chkpwd

    mkdir -pv "${dest_dir}"/etc/pam.d/
    cp -v "${base_dir}"/build-support/pam/* "${dest_dir}"/etc/pam.d/

    post_package_strip
}
