#!/bin/bash

name=pam-bootstrap
from_source=pam
revision=1
bootstrap_pkg=yes
imagedeps="build-essential"
hostdeps="gcc pkgconf"
deps="core-libs gdbm libnsl libtirpc"

configure() {
    meson_configure \
        -Dsecuredir="${prefix}/lib/security" \
        -Dpam_unix=enabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
