#!/bin/bash

name=pixman
version=0.46.4
git_url="https://gitlab.freedesktop.org/pixman/pixman.git"
commit=9cc163c9da0fb4da430641715313d95a6ec466d9
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libpng"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
