#!/bin/bash

name=qt6-wayland
version=6.10.1
git_url="https://code.qt.io/qt/qtwayland.git"
commit="8368f75344ad0376f7656b4c18c87b0ebce2f3e1"
revision=1
imagedeps="pkg-config qt6-base-private-dev"
hostdeps="gcc pkgconf"
deps="core-libs qt6-base qt6-declarative"

configure() {
    # Qt6 handles _FORTIFY_SOURCE internally.
    # Remove any -D_FORTIFY_SOURCE from TARGET_C{,XX}FLAGS to avoid conflicts.
    TARGET_CFLAGS="${TARGET_CFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"
    TARGET_CXXFLAGS="${TARGET_CXXFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"

        PKG_CONFIG="${OS_TRIPLET}-pkg-config" \
    cmake_configure \
        -DQT_HOST_PATH="${build_dir}/host-pkgs/qt6" \
        -DQT_HOST_PATH_CMAKE_DIR="${build_dir}/host-pkgs/qt6/usr/local/lib/cmake"
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
