#!/bin/bash

name=qt6-imageformats
version=6.10.1
git_url="https://code.qt.io/qt/qtimageformats.git"
commit="f24f9588d904294b77368f5dab7114934f9336ae"
revision=1
imagedeps="pkg-config qt6-base-private-dev"
hostdeps="gcc pkgconf"
deps="core-libs libwebp libtiff qt6-base"

configure() {
    # Qt6 handles _FORTIFY_SOURCE internally.
    # Remove any -D_FORTIFY_SOURCE from TARGET_C{,XX}FLAGS to avoid conflicts.
    TARGET_CFLAGS="${TARGET_CFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"
    TARGET_CXXFLAGS="${TARGET_CXXFLAGS//-Wp,-D_FORTIFY_SOURCE=?/}"

        PKG_CONFIG="${OS_TRIPLET}-pkg-config" \
    cmake_configure \
        -DQT_HOST_PATH="${build_dir}/host-pkgs/qt6" \
        -DQT_HOST_PATH_CMAKE_DIR="${build_dir}/host-pkgs/qt6/usr/local/lib/cmake" \
        -DINPUT_webp=system \
        -DINPUT_tiff=system
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
