#!/bin/bash

name=startup-notification
version=0.12
tarball_url="https://www.freedesktop.org/software/startup-notification/releases/startup-notification-${version}.tar.gz"
tarball_blake2b="9822de9745fdeef28d7c6422d2a967394ffc329e7f37e1676c79e900f8e776578698ef47ff199fa05aa795540382f5eab5cb63f6cb20512328897236df1ab152"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11 libice xcb-util"

configure() {
        lf_cv_sane_realloc=yes \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    install -v -m644 -D "${source_dir}/doc/startup-notification.txt" \
        "${dest_dir}${prefix}/share/doc/startup-notification/startup-notification.txt"

    post_package_strip
}
