#!/bin/bash

name=sudo
version=1.9.17p2
tarball_url="https://www.sudo.ws/dist/sudo-${version}.tar.gz"
tarball_blake2b="dd42ff4fd571ba8489cc59d71a09c7e0483d21daf9faf7e697beedc04d9f170b01e60446af179c949a3da115b616fbec07aff8fbf8b7d502161c24d1b35b7a69"
revision=1
imagedeps="build-essential"
hostdeps="gcc pkgconf"
deps="core-libs pam"

configure() {
    autotools_configure \
        --with-pam \
        --with-env-editor \
        --with-passprompt="[sudo] password for %p: " \
        --with-secure-path-value=/usr/local/sbin:/usr/local/bin:/usr/bin \
        --with-all-insults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc/pam.d
    cat <<EOF >"${dest_dir}"/etc/pam.d/sudo
#%PAM-1.0
auth        include system-auth
account     include system-account
password    include system-password
session     include system-session
EOF

    cat <<'EOF' >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/usr/bin:/usr/local/bin:/usr/local/sbin"

ACTION="$1"

case "${ACTION}" in
pre)
    ;;
post)
    groupadd -g 98 sudo
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL

    post_package_strip
}
