#!/bin/bash

name=sway
version=1.11
tarball_url="https://github.com/swaywm/sway/releases/download/${version}/sway-${version}.tar.gz"
tarball_blake2b="98b1f1788df3cd67577f5b3b0db015c27f9a2770ad110c8590bf3f4a35500ec69cf6286b932e63598723e5d190cc9f4ef5711e03aa35bd381fb5d502d09c0c04"
revision=1
imagedeps="libwayland-bin pkg-config"
hostdeps="gcc pkgconf"
deps="
    core-libs
    cairo
    gdk-pixbuf
    json-c
    libevdev
    libinput
    libxcb
    libxkbcommon
    pango
    pcre2
    pixman
    wayland
    wayland-protocols
    wlroots0.19
    xcb-util-wm
"

configure() {
    meson_configure \
        -Dwerror=false \
        -Db_ndebug=true
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
