#!/bin/bash

name=thunar
version=4.21.3
tarball_url="https://archive.xfce.org/src/xfce/thunar/${version%.*}/thunar-${version}.tar.xz"
tarball_blake2b="7b33c494353995646c2dc6ba74610be52e793267da79e7e88821da7951817223707d9b53dc15f6cd249efa38c974fa53845e817bb20bf75b6efb44be4aa1dac1"
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs exo glib2"

configure() {
    meson_configure \
        -Dintrospection=true
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
