#!/bin/bash

name=ttf-dejavu
version=2.37
tarball_url="https://sourceforge.net/projects/dejavu/files/dejavu/${version}/dejavu-fonts-ttf-${version}.tar.bz2"
tarball_blake2b="d8614907887f20967fc7c75cb33b636a0eb5c682a076ccc7aef09f4ac243507afc005ef90d0b2aeee6a4a6a1ff3d5ce4fac0d1722a382525b3883ef53cdec26a"
revision=1
deps="core-libs fontconfig"

build() {
    cp -r ${source_dir}/. ./
}

package() {
    mkdir -p "${dest_dir}${prefix}/share/fonts/truetype"
    cp -r ttf/* "${dest_dir}${prefix}/share/fonts/truetype/"

    cat <<EOF >"${dest_dir}"/INSTALL
#! /bin/sh

export PATH="/usr/bin:/usr/local/bin:/usr/local/sbin"

ACTION="\$1"

case "\${ACTION}" in
pre)
    ;;
post)
    fc-cache -fv
    ;;
esac

exit 0
EOF
    chmod +x "${dest_dir}"/INSTALL
}
