#!/bin/bash

name=vte
version=0.82.3
tarball_url="https://gitlab.gnome.org/api/v4/projects/1893/packages/generic/vte/${version}/vte-${version}.tar.xz"
tarball_blake2b="069c660d2018685bdc748931ffe88299e071bdd68925c6fd92ac43eef8667dd52c0911f66dbb59e6f98a240cb583c102fccb8797d5443e9b1ea83c773f38224b"
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs fast_float simdutf fmt gnutls gtk3 cairo fribidi glib2 icu pango pcre2 lz4 libxml2"

configure() {
    meson_configure \
        -Da11y=true \
        -Ddebug=false \
        -Ddocs=false \
        -Dgir=true \
        -Dfribidi=true \
        -Dglade=true \
        -Dgnutls=true \
        -Dgtk3=true \
        -Dgtk4=false \
        -Dicu=true \
        -D_systemd=false \
        -Dvapi=false
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
