#!/bin/bash

name=xbitmaps
version=1.1.3
tarball_url="https://www.x.org/pub/individual/data/xbitmaps-${version}.tar.gz"
tarball_blake2b="b5bde889f7b821952ec7102c04ee35145e3434e49cb8b6f78de61519f3679a68269fdeb49885be2747288bb66722f954459e65c530058578ab542d9750a2a5a8"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs xorg-util-macros"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
