#!/bin/bash

name=xfce4-panel
version=4.21.0
tarball_url="https://archive.xfce.org/src/xfce/xfce4-panel/4.21/xfce4-panel-${version}.tar.xz"
tarball_blake2b="cf06cd31589e3f2ce854df7677e6ae54e59432f69cb552a1bd4069798d61a287b0e476e355a3f65c5862134b8a1b1b231fe5660fa7a1e306ca912da5796b4d5e"
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs cairo exo garcon glib2 libwnck libxfce4windowing"

configure() {
    meson_configure \
        -Dintrospection=true \
        -Dx11=enabled
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
