#!/bin/bash

name=xfce4-terminal
version=1.1.5
tarball_url="https://archive.xfce.org/src/apps/xfce4-terminal/${version%.*}/xfce4-terminal-${version}.tar.xz"
tarball_blake2b="d17a90a89e883d274e63ccba8332fc5b4caf4a9fab50eed26afc1401795df305ba4190cfb8e653b7a2730226dd3f6a870e32581a0c5ba2d660cbe79000ba9a54"
revision=1
imagedeps="libglib2.0-dev-bin"
hostdeps="gcc pkgconf"
deps="core-libs libxfce4ui vte"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
