#!/bin/bash

name=xfce4-session
version=4.21.1
tarball_url="https://archive.xfce.org/src/xfce/xfce4-session/${version%.*}/xfce4-session-${version}.tar.xz"
tarball_blake2b="aeb180fe82ae0f1b874c64b2e5bbc0cbe45f9b032ab60625faad93bf6ae4e2fdde096e0b17d0689ddbfe81eb09eaa831b10a9971f93935fe137ddb15c91f9c5b"
revision=1
# libgdk-pixbuf2.0-bin is needed for gdk-pixbuf-csource, x11-xserver-utils is needed for iceauth
imagedeps="libgdk-pixbuf2.0-bin libglib2.0-dev-bin x11-xserver-utils"
hostdeps="gcc pkgconf"
deps="core-libs libwnck libxfce4ui xfdesktop xorg-iceauth"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
