#!/bin/bash

name=xfconf
version=4.21.0
git_url="https://gitlab.xfce.org/xfce/xfconf.git"
commit=aa1a5b5f327c616eb8d5abe4d458d971461f0576
revision=1
imagedeps="build-essential patchelf"
hostdeps="gcc pkgconf gobject-introspection"
deps="core-libs glib2 libxfce4util"

configure() {
    meson_configure \
        -Dintrospection=true
}

build() {
    goi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
