#!/bin/bash

name=xfdesktop
version=4.20.1
tarball_url="https://archive.xfce.org/src/xfce/xfdesktop/${version%.*}/xfdesktop-${version}.tar.bz2"
tarball_blake2b="b9ce68433181221c20b15bab27d1652ef044b0a1524d9acfbff12b40034f629af8b99eebb6b8874816cc37f4db4874ceca03eec51c7cf091795f0b934d3fd20b"
revision=2
imagedeps="libglib2.0-dev-bin"
hostdeps="gcc pkgconf"
deps="core-libs exo gtk3 gtk-layer-shell libnotify libwnck libxfce4ui libxfce4util libxfce4windowing libyaml"

configure() {
    meson_configure \
        -Ddefault-backdrop-filename=backgrounds/xfce/xfce-shapes.svg \
        -Dtests=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
