#!/bin/bash

name=xorg-server
version=21.1.21
git_url="https://gitlab.freedesktop.org/xorg/xserver.git"
commit=312a25c65c8a918fea2cc77abd0db07ec0fc421c
revision=4
hostdeps="gcc pkgconf"
deps="
    core-libs
    dbus
    libdrm
    libepoxy
    libpciaccess
    libx11
    libxaw
    libxcb
    libxcvt
    libxdamage
    libxext
    libxfixes
    libxfont2
    libxi
    libxinerama
    libxkbfile
    libxmu
    libxrandr
    libxrender
    libxres
    libxshmfence
    libxv
    libxxf86vm
    nettle
    pixman
    udev
    xcb-proto
    xcb-util
    xkeyboard-config
    xorg-font-util
    xorg-proto
    xorg-util-macros
    xorg-xkbcomp
    xtrans
"

configure() {
    meson_configure \
        -Dxkb_bin_dir="${prefix}/bin" \
        -Dxkb_dir="${prefix}/share/X11/xkb" \
        -Dxkb_output_dir=/var/lib/xkb \
        -Ddefault_font_path="${prefix}/share/fonts/X11" \
        -Dxorg=true \
        -Dxv=true \
        -Dxvfb=true \
        -Dxephyr=false \
        -Dxnest=false \
        -Dsuid_wrapper=false \
        -Dpciaccess=true \
        -Ddpms=true \
        -Dscreensaver=true \
        -Dxres=true \
        -Dxvmc=false \
        -Dsystemd_logind=false \
        -Dsecure-rpc=false \
        -Dudev=true \
        -Dudev_kms=true \
        -Ddri1=true \
        -Ddri2=true \
        -Ddri3=true \
        -Dvgahw=true \
        -Ddrm=true \
        -Dglamor=false \
        -Dglx=true

    # HACK: pkgconf prepends paths with sysroot dir, so we need to fix them
    # in the generated dix-config.h file, otherwise dri drivers won't be loaded
    sed -i "s|/sysroot||g" include/dix-config.h
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
