#!/bin/bash

name=xorg-xclock
version=1.1.1
tarball_url="https://xorg.freedesktop.org/archive/individual/app/xclock-${version}.tar.gz"
tarball_blake2b="4fd77b8f1f0962774dd0e6295f7482c05be8107e1606a9705ccd2864d2c9b37adda4a41a6704c6e1363edd2b7e704324799c4feaff39e218b326b66274b48187"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11 libxaw libxft libxkbfile libxmu libxrender"

configure() {
    autotools_configure \
        --with-appdefaultdir=/etc/X11/app-defaults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
