#!/bin/bash

name=xorg-util-macros
version=1.20.2
tarball_url="https://www.x.org/archive/individual/util/util-macros-${version}.tar.gz"
tarball_blake2b="57c880e87b7714234d220897736864401277a609a2038a018b551f495868c6ac9ef3257a8df367369635a304440386877f287dd7d27e42616def00ec1dc1b55e"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
