#!/bin/bash

name=xorg-xwayland
version=24.1.9
tarball_url="https://www.x.org/pub/individual/xserver/xwayland-${version}.tar.xz"
tarball_blake2b="f445efb5f09d6516f01f0a3f2b68d363ea3f5b82b199d9cef6b5d442885d1d34489d60f2bb8cd8ac3dc7077b5b9d4532ebf3c18d7313a584e9a35f5f5c416273"
revision=1
imagedeps="pkg-config libwayland-bin"
hostdeps="gcc pkgconf"
deps="
    core-libs
    freetype2
    harfbuzz
    libdrm
    libepoxy
    libgcrypt
    libglvnd
    libtirpc
    libxau
    libxcvt
    libxfont2
    mesa
    nettle
    pixman
    wayland-protocols
    xorg-xkbcomp
"

configure() {
    meson_configure \
        -Dxvfb=false \
        -Dxkb_dir="${prefix}/share/X11/xkb" \
        -Dxkb_output_dir=/var/lib/xkb
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    rm -rv ${dest_dir}${prefix}/lib/xorg
    # This will be installed by xorg-server
    rm -v ${dest_dir}${prefix}/share/man/man1/Xserver.1

    post_package_strip
}
