#!/bin/bash

name=xorg-xrandr
version=1.5.3
tarball_url="https://www.x.org/pub/individual/app/xrandr-${version}.tar.xz"
tarball_blake2b="a2f253e0027976ef1bbf346361f6cfcfb575db36f134ec21e234f733fe7e70959d401c6b078a0d6d0297021aeff12eef57e4fdc865c86531784e439927385995"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11 libxaw libxmu libxrandr libxt"

configure() {
    autotools_configure \
        --with-appdefaultdir=/etc/X11/app-defaults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
