#!/bin/bash

name=xorg-xmodmap
version=1.0.11
tarball_url="https://www.x.org/releases/individual/app/xmodmap-${version}.tar.xz"
tarball_blake2b="d50611e762b665b18c370ea49d981d7820f16e2e10450bbb2ebc76c867a3a4e75d68e7dacfb9e610849770afa95f4d757863953217aac8e13509b386bdb8131d"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
