#!/bin/bash

name=xorg-xrdb
version=1.2.2
tarball_url="https://www.x.org/releases/individual/app/xrdb-${version}.tar.xz"
tarball_blake2b="fbf396089a82db2a21866527f7d847f106164e1ce10795a2f96e34d5165311f4ed718eee10429792fc4fe273529af3350c41d765cb067c6310707bcc976bfdbe"
revision=1
hostdeps="gcc pkgconf"
deps="core-libs libx11 libxmu"

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
