#!/bin/bash

name=automake
from_source=automake
revision=1
hostdeps="autoconf"
imagedeps="build-essential"

configure() {
        CFLAGS="${HOST_CFLAGS}" \
        CXXFLAGS="${HOST_CXXFLAGS}" \
        LDFLAGS="${HOST_LDFLAGS}" \
    "${source_dir}"/configure \
        --prefix="${prefix}"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
