#!/bin/bash

name=gobject-introspection
from_source=gobject-introspection
revision=1
imagedeps="build-essential libffi-dev libpcre2-dev libpython3-dev pkg-config"
hostdeps="gcc glib2"

configure() {
    meson setup "${source_dir}" \
        --prefix="${prefix}" \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libdir=lib \
        --sbindir=bin \
        --buildtype=release \
        -Ddefault_library=shared \
        -Dgtk_doc=false \
        -Dbuild_introspection_data=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
